### ISSUE TITLE
double scrollbar with firefox 

### ISSUE THREAD

**Issue by raffis** [gyselroth/balloon-client-web#191] opened 2019-05-24 08:31 UTC
#### Describe the bug
![Selection_018](https://user-images.githubusercontent.com/2376735/58314085-15641300-7e0f-11e9-82e1-7475e8cba6ce.jpg)

#### Environment
 - web-client version: v3.2.0-alpha1
 - balloon server version: [e.g. v2.4.2]
 - Deployed as: [e.g. docker,deb package,tar,compiled manually]
 - client os: Linux Mint 19.2
 - browser: Firefox 66

**Comment by pixtron** [comment] 2019-05-25 06:52
Probably a duplicate of #167

**Closed** 2019-06-25 08:41 UTC
Labels: bug, hasfix
